version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=psql://postgres:postgres@db:5432/postgres
      - SECRET_KEY="django-insecure-2!^@v%5cwto)qJ&-n%5hop868jm6r6lzl_3^wy@ykuhd87j&ya"
      - DEBUG=True
      - ALLOWED_HOSTS=*
    depends_on:
      - db

volumes:
  postgres_data: